# Heroku overwrites this file when app is deployed
development:
  adapter: postgresql
  database: engine-light_development
  encoding: unicode
  username: engine_light
  password:
  host: localhost

test:
  adapter: postgresql
  database: engine-light_test
  encoding: unicode
  username: postgres
  password:
  host: localhost

production:
  adapter: postgresql
  database: engine-light_production
  encoding: unicode
  username: engine_light
  password: password
